import { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
  overwrite: true,
  schema: 'graphql/*.graphql',
  generates: {
    './packages/lib-ts-service/src/graphql/__generated__/schema.ts': {
      plugins: [
        {
          add: {
            content: '/* eslint-disable */',
          },
        },
        {
          add: {
            content: '/* Generated by @graphql-codegen */',
          },
        },
        'typescript',
        'typescript-resolvers',
      ],
    },
    './packages/lib-ts-service/src/graphql/__generated__/typeDefs.ts': {
      plugins: [
        {
          add: {
            content: '/* eslint-disable */',
          },
        },
        {
          add: {
            content: '/* Generated by @graphql-codegen */',
          },
        },
        './.codegen/codegen-typedefs.js',
      ],
    },
  },
};

export default config;
